{% set name = "duckdb" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  # (!!) Please also update the git used for OVERRIDE_GIT_DESCRIBE in the build scripts.
  url: https://github.com/duckdb/duckdb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 662a0ba5c35d678ab6870db8f65ffa1c72e6096ad525a35b41b275139684cea6
  patches:
    - 0001-Dynamically-link-the-cli.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - openssl

outputs:
  - name: libduckdb
    script: install-lib.sh
    build:
      run_exports:
        - {{ pin_subpackage("libduckdb", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - openssl
    test:
      commands:
        - test -f $PREFIX/lib/libduckdb${SHLIB_EXT}
  - name: libduckdb-devel
    script: install-headers.sh
    build:
      run_exports:
        - {{ pin_subpackage("libduckdb", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/duckdb.h
  - name: duckdb-cli
    script: install-cli.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
        - duckdb -version
  - name: duckdb-extension-json
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
    test:
      commands:
          - find "${PREFIX}"/duckdb/extensions/v{{ version }}/ -type f -name 'json.duckdb_extension' | grep '.'
          - if [ "$(duckdb -json -c "set extension_directory='${PREFIX}/duckdb/extensions'; select extension_name from duckdb_extensions() where (installed and install_path != '(BUILT-IN)');" | jq -r '.[].extension_name')" = "json" ]; then exit 0; else exit 1; fi
      requires:
        - duckdb-cli
        - jq
  - name: duckdb-extension-httpfs
    script: install-extension.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage("libduckdb", exact=True) }}
      run:
        - {{ pin_subpackage("libduckdb", exact=True) }}
        - openssl
    test:
      commands:
          - find "${PREFIX}"/duckdb/extensions/v{{ version }}/ -type f -name 'httpfs.duckdb_extension' | grep '.'
          - if [ "$(duckdb -json -c "set extension_directory='${PREFIX}/duckdb/extensions'; select extension_name from duckdb_extensions() where (installed and install_path != '(BUILT-IN)');" | jq -r '.[].extension_name')" = "httpfs" ]; then exit 0; else exit 1; fi
      requires:
        - duckdb-cli
        - jq

about:
  home: https://www.duckdb.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An Embeddable Analytical Database
  description: |
    DuckDB is an embedded database designed to execute analytical SQL queries
    fast while embedded in another process. It is designed to be easy to
    install and easy to use.
  doc_url: https://duckdb.org/docs/index.html
  dev_url: https://github.com/duckdb/duckdb

extra:
  recipe-maintainers:
    - xhochy
